version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: credis
  backend:
    image: koak/ak-lab2-backend:backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://dbuser:dbpass@cdatabase:3306/mydb=value
      - REDIS_HOST=credis
    container_name: cbackend
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb=value
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
    container_name: cdatabase