name: Build & Push backend Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildb:
    runs-on: vm3
    Environment: DVM
    env:
      VM_USR: ${{ secret.VM_USER }}
      VM_PA: ${{ secret.VM_PASS }}
    steps:
      -uses: actions/checkout@v4
      -name: docker login
      run: |
      docker logout
      echo "${{ env.VM_PA }}" | docker login -u "${{ env.VM_USR }}" --password-stdin
      - name: build & push
      working-directory: ./
      run: |
      docker rmi bimg || true
      docker rmi koak/ak-lab2-backend:backend || true
      docker build -t bimg .
      docker tag bimg koak/ak-lab2-backend:backend
      docker push koak/ak-lab2-backend:backend