name: Build & Push backend Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildb:
    runs-on: runb
    environment: DVM
    env:
      VM_USR: ${{ secrets.VM_USER }}
      VM_PA: ${{ secrets.VM_PASS }}
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      run: |
         docker logout
         echo "${{ env.VM_PA }}" | docker login -u "${{ env.VM_USR }}" --password-stdin
    - name: build & push
      working-directory: ./
      run: |
         docker rmi bimg || true
         docker rmi koak/ak-lab2-backend:backend || true
         docker build -t bimg .
         docker tag bimg koak/ak-lab2-backend:backend
         docker push koak/ak-lab2-backend:backend
    - name: pull & deploy vm2
      run: |
         scp -i ./sshkeys/vmkey /home/v3/backend/docker-compose.yml v2@192.168.0.169:./
         ssh -i ./sshkeys/vmkey v2@192.168.0.169
         docker rmi redis:alpine || true
         docker stop credis || true
         docker rm credis || true
         docker rmi koak/ak-lab2-backend:backend || true
         docker stop cbackend || true
         docker rm cbackend || true
         docker rmi mysql:8.0 || true
         docker stop cdatabase || true
         docker rm cdatabase || true
         docker compose up -d
      
